# Generated by Django 5.2.15 on 2026-07-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'हिंदी'), ('mr', 'मराठी'), ('bn', 'বাংলা'), ('te', 'తెలుగు'), ('ta', 'தமிழ்'), ('gu', 'ગુજરાતી'), ('kn', 'ಕನ್ನಡ'), ('ml', 'മലയാളം'), ('pa', 'ਪੰਜਾਬੀ'), ('or', 'ଓଡ଼ିଆ'), ('as', 'অসমীয়া')], default='en', max_length=5),
        ),
    ]
